"""drop about_company selling_points tone from sequences

Revision ID: 48e13ba09f3d
Revises: f8e3a91c2b04
Create Date: 2026-03-25 20:41:36.865735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e13ba09f3d'
down_revision: Union[str, Sequence[str], None] = 'f8e3a91c2b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequences', 'about_company')
    op.drop_column('sequences', 'selling_points')
    op.drop_column('sequences', 'tone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequences', sa.Column('about_company', sa.Text(), nullable=True))
    op.add_column('sequences', sa.Column('selling_points', sa.Text(), nullable=True))
    op.add_column('sequences', sa.Column('tone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###
