"""initial schema

Revision ID: b65bf38f5422
Revises: 
Create Date: 2026-03-25 14:58:13.572712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65bf38f5422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_candidates_email', 'candidates', ['email'], unique=False)
    op.create_table('nylas_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('about_company', sa.Text(), nullable=True),
    sa.Column('selling_points', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('next_send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=255), nullable=True),
    sa.Column('nudge_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nudge_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'sequence_id', name='uq_enrollment_candidate_sequence')
    )
    op.create_index('ix_enrollments_status_next_send', 'enrollments', ['status', 'next_send_at'], unique=False)
    op.create_index(op.f('ix_enrollments_unsubscribe_token'), 'enrollments', ['unsubscribe_token'], unique=False)
    op.create_table('sequence_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=30), nullable=True),
    sa.Column('sentiment_reasoning', sa.Text(), nullable=True),
    sa.Column('nylas_message_id', sa.String(length=255), nullable=True),
    sa.Column('nylas_thread_id', sa.String(length=255), nullable=True),
    sa.Column('is_manual_reply', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nylas_message_id', name='uq_email_events_message_id')
    )
    op.create_index('ix_email_events_thread', 'email_events', ['nylas_thread_id'], unique=False)
    op.create_table('state_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referrer_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('referred_candidate_id', sa.Uuid(), nullable=False),
    sa.Column('source_email_event_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referred_candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['referrer_candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['source_email_event_id'], ['email_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    op.drop_table('state_transitions')
    op.drop_index('ix_email_events_thread', table_name='email_events')
    op.drop_table('email_events')
    op.drop_table('sequence_steps')
    op.drop_index(op.f('ix_enrollments_unsubscribe_token'), table_name='enrollments')
    op.drop_index('ix_enrollments_status_next_send', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_table('sequences')
    op.drop_table('nylas_accounts')
    op.drop_index('ix_candidates_email', table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
