"""add unique constraint on nylas_accounts email

Revision ID: b92a8fc579c8
Revises: 2fd7137c1f5a
Create Date: 2026-03-26 13:45:16.915642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b92a8fc579c8'
down_revision: Union[str, Sequence[str], None] = '2fd7137c1f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nylas_accounts', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nylas_accounts', type_='unique')
    # ### end Alembic commands ###
